'component/api':
- 'api/*'
- 'api/**/*'

'component/cli':
- 'cli/*'
- 'cli/**/*'

'kind/documentation':
- 'website/*'
- 'website/**/*'
- 'website/**/**/*'
- '**/*.md'

'provider/azure':
- 'api/azure/*'

'provider/civo':
- 'api/civo/*'

'provider/local':
- 'api/local/*'

