name: codecov
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  codecov:
    name: codecov coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: ./website
    - uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
